development:
  app_id: Muso8IFDYAukQ92C6PA6s307V1Tk4vUYoKu0oNss
  master_key: yNSU7hdggeDRlayaOaQHrWoiT9Gfs5ujCu47rsVG

test:
  app_id: Muso8IFDYAukQ92C6PA6s307V1Tk4vUYoKu0oNss
  master_key: yNSU7hdggeDRlayaOaQHrWoiT9Gfs5ujCu47rsVG

production:
  app_id: Muso8IFDYAukQ92C6PA6s307V1Tk4vUYoKu0oNss
  master_key: yNSU7hdggeDRlayaOaQHrWoiT9Gfs5ujCu47rsVG
